services:
  web:
    build: . 
    volumes:
      - ./app:/app/app 
    command: /bin/sh -c "alembic upgrade head || { echo 'Migration failed'; exit 1; } && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000" 
    depends_on:
      - db
    env_file:
        - .env

  db:
    image: postgres:alpine  
    restart: always
    env_file:
        - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data: