"""Initial migration

Revision ID: 1c9d0b723284
Revises: 2b812a47f972
Create Date: 2025-04-13 16:32:57.770277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9d0b723284'
down_revision: Union[str, None] = '2b812a47f972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tables_name', table_name='tables')
    op.create_index(op.f('ix_tables_name'), 'tables', ['name'], unique=True)
    op.create_unique_constraint(None, 'tables', ['location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='unique')
    op.drop_index(op.f('ix_tables_name'), table_name='tables')
    op.create_index('ix_tables_name', 'tables', ['name'], unique=False)
    # ### end Alembic commands ###
